parameters:
    currencyRateProviders:
        !php/const App\Provider\Monobank\Monobank::NAME: App\Provider\Monobank\Monobank

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
